name = "xenni-website"
type = "javascript"

[build]
command = "npm run build"
cwd = "."

# wrangler.toml
name = 'xennilandingai2'

[env.production]
name = "xenni-website-prod"

[env.staging]
name = "xenni-website-staging"
